#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
//* The program that makes the summation of odd numbers which are generated by rand()
//* The program will stop when the sum is over than 100
int getRand(void);
bool isoddNum(int);
int main()
{
    int sum=0, rdnum;
    srand(time(0));

    while ( sum < 100) {
        rdnum = getRand();
        cout << rdnum << " is generated\n";
        if ( isoddNum(rdnum) ){
            sum += rdnum;
            cout << rdnum << " is added and now the sum is " << sum << endl;
        }
    }
    cout << "Total Sum is " << sum << endl;
}
int getRand()
{
    return rand() % 100 + 1;
}
bool isoddNum(int n)
{
    return (n%2) ? 1 : 0;
}